### ISSUE TITLE
Are you here?

### ISSUE THREAD

**Issue by GollyJer** [ahrnee/graphql-codegen-hasura#2]
Hi @ahrnee. Just wondering if there's any way to communicate and give feedback. Do you check Issues? Is there a better way?

**Comment by ahrnee** [comment]
Hi @GollyJer - sorry just noticed this. I'll keep an eye on the issues section now I know they are getting used.

**Comment by GollyJer** [comment]
Excellent! I'll give things another try today and let you know if I run into any issues.
I ran into this on my first attempt.
https://github.com/ahrnee/graphql-codegen-hasura/issues/1

And had a different issue on my second attempt.

But, you've iterated a lot since then... I'll keep you posted. I'm super excited to get something like this up and working. It is a really good idea and should make coding simpler.

**Comment by ahrnee** [comment]
Thanks! It will be useful getting feedback from someone else using it. 

Figuring out how to get Lerna/NPM/TypeScript all playing together nicely was one of the most challenging parts. I *think* I have figured that part out now, but if you are running into issues there I would definitely like to know.

**Comment by GollyJer** [comment]
Cool. I'm hoping to get to it this weekend.

You might want to check out Yarn 2. Facebook uses monorepos and it looks like they build yarn 2's `workspaces` feature, and the script handling, to help with your type of setup.
[Introducing Yarn 2[(https://dev.to/arcanis/introducing-yarn-2-4eh1)

**Comment by ahrnee** [comment]
@GollyJer - thanks for the heads-up on Yarn2. That looks great. I'll investigate switching at some point. I personally have always prefered Yarn to NPM. I recently switched because Lerna and NPM seemed to (surprisingly) have better compatibity - in particular the support for lifecycle scripts (I used the prepublishOnly tag). It looks like Yarn2 could completley replace Lerna which would sidestep that problem all together!
